#!/usr/bin/env node
/**
 * Full Senyum logo pipeline.
 *
 * Builds the wordmark from Switzer Bold outlines (src/fonts/switzer/Switzer-Bold.ttf)
 * plus the smile arc, then writes:
 *   src/components/brand/logo-paths.ts   LOGO_HORIZONTAL, LOGO_STACKED, LOGO_MARK
 *   brand/logo-{horizontal,stacked,mark}{,-navy,-white}.svg
 *   src/app/icon.svg, src/app/favicon.ico (16/32/48), src/app/apple-icon.png (180)
 *   public/icon-192.png, public/icon-512.png
 *
 * Tooling is deliberately NOT in package.json. Install it anywhere and point
 * LOGO_TOOLS at that node_modules' parent, e.g.
 *   mkdir -p /tmp/logo-tools && npm i --prefix /tmp/logo-tools opentype.js@1 @resvg/resvg-js@2
 *   LOGO_TOOLS=/tmp/logo-tools node tools/logo/generate.mjs
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const require = createRequire(
  process.env.LOGO_TOOLS ? join(resolve(process.env.LOGO_TOOLS), "package.json") : import.meta.url,
);
let opentype, Resvg;
try {
  opentype = require("opentype.js");
  ({ Resvg } = require("@resvg/resvg-js"));
} catch {
  console.error("Missing tooling. See the header of tools/logo/generate.mjs (LOGO_TOOLS).");
  process.exit(1);
}

const NAVY = "#0D1B3E";
const WHITE = "#FFFFFF";
const font = opentype.loadSync(join(root, "src/fonts/switzer/Switzer-Bold.ttf"));
const SIZE = 100; // font size in logo units

/** Glyph outlines for `text`, one path per visible character, kerned. */
function layout(text, x0, baseline) {
  const glyphs = font.stringToGlyphs(text);
  const out = [];
  let x = x0;
  glyphs.forEach((glyph, i) => {
    if (text[i] !== " ") {
      const path = glyph.getPath(x, baseline, SIZE);
      out.push({ ch: text[i], d: path.toPathData(2), bb: path.getBoundingBox() });
    }
    x += (glyph.advanceWidth / font.unitsPerEm) * SIZE;
    if (i < glyphs.length - 1) x += (font.getKerningValue(glyph, glyphs[i + 1]) / font.unitsPerEm) * SIZE;
  });
  return out;
}

/** The smile: a crescent from xa to xb, `depth` deep, `t` thick, slanted ends. */
function smile(xa, xb, y, depth, t) {
  const xm = (xa + xb) / 2;
  const r = (n) => n.toFixed(2);
  return (
    `M${r(xa)} ${r(y)}Q${r(xm)} ${r(y + depth * 2)} ${r(xb)} ${r(y)}` +
    `L${r(xb - t * 0.2)} ${r(y + t)}Q${r(xm)} ${r(y + depth * 2 + t * 0.9)} ${r(xa + t * 0.2)} ${r(y + t)}Z`
  );
}

function bounds(letters, extraY = []) {
  const xs = letters.flatMap((q) => [q.bb.x1, q.bb.x2]);
  const ys = letters.flatMap((q) => [q.bb.y1, q.bb.y2]).concat(extraY);
  const minX = Math.min(...xs);
  const minY = Math.min(...ys);
  const w = +(Math.max(...xs) - minX).toFixed(2);
  const h = +(Math.max(...ys) - minY).toFixed(2);
  return { viewBox: `${minX.toFixed(2)} ${minY.toFixed(2)} ${w} ${h}`, width: Math.round(w), height: Math.round(h) };
}

/** Wordmark: the smile runs from under "e" to under "u" of "Senyum". */
function wordmark(lines) {
  const letters = [];
  let senyum = [];
  for (const [text, x0, base] of lines) {
    const glyphs = layout(text, x0, base);
    letters.push(...glyphs);
    if (text.includes("Senyum")) senyum = glyphs.slice(glyphs.findIndex((q) => q.ch === "S"));
  }
  const e = senyum[1].bb;
  const u = senyum[4].bb;
  const base = Math.max(...senyum.filter((q) => q.ch !== "y").map((q) => q.bb.y2));
  const arc = smile(e.x1 + 2, u.x2 - 2, base + 6, 7, 7);
  return { ...bounds(letters, [base + 6 + 14 + 7]), letters: letters.map((q) => q.d), smile: arc };
}

/** Compact mark for small sizes: the "S" of Senyum over a heavier smile. */
function mark() {
  const [s] = layout("S", 0, 100);
  const { x1, x2, y1, y2 } = s.bb;
  const t = 11; // thicker than the wordmark's smile so it survives 16px
  const depth = 9;
  const y = y2 + 9;
  const xa = x1 - 5;
  const xb = x2 + 5;
  const arc = smile(xa, xb, y, depth, t);
  const top = y1;
  const bottom = y + depth + 0.95 * t; // lowest point of the inner curve
  const w = xb - xa;
  const h = bottom - top;
  const side = Math.max(w, h);
  const vx = xa - (side - w) / 2;
  const vy = top - (side - h) / 2;
  return { viewBox: `${vx.toFixed(2)} ${vy.toFixed(2)} ${side.toFixed(2)} ${side.toFixed(2)}`, paths: [s.d, arc] };
}

const HORIZONTAL = wordmark([["Full Senyum", 0, 100]]);
const STACKED = wordmark([["Full", 0, 100], ["Senyum", 0, 190]]);
const MARK = mark();

// --- logo-paths.ts -----------------------------------------------------------
const ts = `/**
 * Full Senyum logo artwork, generated by tools/logo/generate.mjs from Switzer
 * Bold outlines plus the smile arc. Do not edit by hand; re-run the script.
 * letters = one path \`d\` per glyph in reading order (staggered animation);
 * smile = the arc under "Senyum".
 */
export type LogoArt = { viewBox: string; width: number; height: number; letters: string[]; smile: string };

export const LOGO_HORIZONTAL: LogoArt = ${JSON.stringify(HORIZONTAL, null, 2)};

export const LOGO_STACKED: LogoArt = ${JSON.stringify(STACKED, null, 2)};

/** Compact mark ("S" + smile) for favicons and very small placements. */
export const LOGO_MARK: { viewBox: string; paths: string[] } = ${JSON.stringify(MARK, null, 2)};
`;
writeFileSync(join(root, "src/components/brand/logo-paths.ts"), ts);

// --- SVG helpers -------------------------------------------------------------
const vb = (viewBox) => viewBox.split(" ").map(Number);
const artPaths = (art) => (art.paths ?? [...art.letters, art.smile]).map((d) => `<path d="${d}"/>`).join("");

function logoSvg(art, fill, title = "Full Senyum") {
  const [, , w, h] = vb(art.viewBox);
  return (
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${art.viewBox}" width="${Math.round(w)}" height="${Math.round(h)}" ` +
    `fill="${fill}" role="img" aria-label="${title}"><title>${title}</title>${artPaths(art)}</svg>\n`
  );
}

/** Artwork centred on a square tile; `scale` = share of the tile the art may occupy. */
function tileSvg(art, size, { bg, fg, scale }) {
  const [x, y, w, h] = vb(art.viewBox);
  const k = (size * scale) / Math.max(w, h);
  const tx = (size - w * k) / 2 - x * k;
  const ty = (size - h * k) / 2 - y * k;
  return (
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${size} ${size}" width="${size}" height="${size}">` +
    `<rect width="${size}" height="${size}" fill="${bg}"/>` +
    `<g fill="${fg}" transform="translate(${tx.toFixed(2)} ${ty.toFixed(2)}) scale(${k.toFixed(5)})">${artPaths(art)}</g></svg>\n`
  );
}

const png = (svg, size) => new Resvg(svg, { fitTo: { mode: "width", value: size } }).render().asPng();

/** ICO container with PNG-encoded entries (supported by every current browser). */
function ico(images) {
  const header = Buffer.alloc(6);
  header.writeUInt16LE(0, 0);
  header.writeUInt16LE(1, 2);
  header.writeUInt16LE(images.length, 4);
  let offset = 6 + 16 * images.length;
  const entries = images.map(({ size, data }) => {
    const e = Buffer.alloc(16);
    e.writeUInt8(size % 256, 0);
    e.writeUInt8(size % 256, 1);
    e.writeUInt16LE(1, 4);
    e.writeUInt16LE(32, 6);
    e.writeUInt32LE(data.length, 8);
    e.writeUInt32LE(offset, 12);
    offset += data.length;
    return e;
  });
  return Buffer.concat([header, ...entries, ...images.map((i) => i.data)]);
}

// --- brand/ exports -----------------------------------------------------------
mkdirSync(join(root, "brand"), { recursive: true });
for (const [name, art] of [["horizontal", HORIZONTAL], ["stacked", STACKED], ["mark", MARK]]) {
  writeFileSync(join(root, `brand/logo-${name}.svg`), logoSvg(art, "currentColor"));
  writeFileSync(join(root, `brand/logo-${name}-navy.svg`), logoSvg(art, NAVY));
  writeFileSync(join(root, `brand/logo-${name}-white.svg`), logoSvg(art, WHITE));
}

// --- icons ----------------------------------------------------------------------
// Tabs and bookmarks: the compact mark, white on navy (reads on light and dark tab strips).
const favicon = (size) => tileSvg(MARK, size, { bg: NAVY, fg: WHITE, scale: 0.8 });
writeFileSync(join(root, "src/app/icon.svg"), favicon(32));
writeFileSync(
  join(root, "src/app/favicon.ico"),
  ico([16, 32, 48].map((size) => ({ size, data: png(favicon(size), size) }))),
);
// Home-screen icons: the stacked wordmark, white on navy, inside the maskable safe zone.
const appIcon = (size) => tileSvg(STACKED, size, { bg: NAVY, fg: WHITE, scale: 0.62 });
writeFileSync(join(root, "src/app/apple-icon.png"), png(appIcon(180), 180));
writeFileSync(join(root, "public/icon-192.png"), png(appIcon(192), 192));
writeFileSync(join(root, "public/icon-512.png"), png(appIcon(512), 512));

// Contact sheet for a visual check (not shipped).
if (process.env.LOGO_PREVIEW) {
  for (const size of [16, 32, 48]) writeFileSync(join(process.env.LOGO_PREVIEW, `favicon-${size}.png`), png(favicon(size), size));
  writeFileSync(join(process.env.LOGO_PREVIEW, "favicon-sheet.png"), png(favicon(32), 256));
}

console.log("logo-paths.ts, brand/*.svg, favicons and app icons written.");
console.log(`horizontal ${HORIZONTAL.viewBox} · stacked ${STACKED.viewBox} · mark ${MARK.viewBox}`);
